apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NicolasMunoz13/guestbook.git
    path: guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncWindows:
  - applications:
      - guestbook
    duration: 24h
    kind: deny
    schedule: '* * * * *'
    timeZone: America/Bogota